name: enough_icalendar
description: iCalendar library to parse, generate and respond to iCal / ics
  invites. Fully compliant with RFC 5545 (iCalendar) and RFC 5546 (iTIP). Forked.
version: 0.16.0
homepage: https://github.com/VisualSystemsCorp/enough_icalendar
topics:
 - icalendar
 - ics
 - ical
 - rfc5545
 - rfc5546

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  lints:
  test:
